services:
  asizoydb:
    image: mariadb
    container_name: asizoy-db
    environment:
      MARIADB_DATABASE: 'asizoydb'
      MARIADB_USER: 'asizoyuser'
      MARIADB_PASSWORD: 'userpwrd'
      MARIADB_ROOT_PASSWORD: 'rootpwrd'
    ports:
      - '3306:3306'
    volumes:
      - './mariadb_data:/var/lib/mysql'